# Assigns Storage Blob Data Contributor to test-app's WorkloadIdentity
# on the test-app-data BlobStorage container.
apiVersion: azure.p6m.dev/v1alpha1
kind: IdentityRoleAssignment
metadata:
  name: test-app-data-blobstorage-write
  labels:
    p6m.dev/app: test-app
spec:
  parameters:
    identityName: test-app
    resourceType: blobstorage
    resourceName: test-app-data
    access: write
