# Environment-specific Kustomization
# Variables: dev (dev, stg, prd)
#
# This references the base and applies the environment-specific patch.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patchesStrategicMerge:
  - application_patch.yaml
