---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - namespace.yaml

# Solution-scoped namespace (see dev overlay for rationale).
namespace: ybor-playground-test-app-stg

patches:
  - path: application_patch.yaml
